<?php
 /**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * The template used for displaying page content in single.php
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
?>

                <div class="col-sm-12">
                    <div class="testimonial">
                        <div class="testimonial-content">
                            <strong class="dz-testimonial__quote"><?php the_field('testimonial_quote'); ?></strong>

                            <?php if (get_field('full_testimonial')): ?>
                                <p class="dz-testimonial__full"><?php the_field('full_testimonial'); ?></p>
                            <?php endif; ?>

                            <div class="t-author">
                                <?php 
                                $img_url = wp_get_attachment_url( get_field('photo'),'full');
                                $image = aq_resize( $img_url, 85, 84, true );
                                ?>
                                <?php if($img_url): ?>
                                <div class="author-img-wrapper">
                                    <img src="<?=$image?>" alt="<?=$image?>" class="img-circle" />
                                </div>
                                <?php endif; ?>
                                <div class="rate-about">
                                    
                                    <span class="dz-testimonial__author">
                                    <?php the_title(); ?>
                                    </span>
                                    
                                </div>
                            </div>
                    
                            <!-- include custom style -->
                            <?php 

                            if ( get_field( 'is-style' ) ) {
                                echo Testimonial::get_styles( get_field( 'testimonial-style' ) );
                                ?>
                                    <script>
                                        ;(function($){
                                            $(function(){
                                                $('html').addClass('<?php the_field( 'testimonial-style' ); ?>');
                                            });
                                        })(jQuery);
                                    </script>

                                <?php
                            }
                            ?>
                        </div>
                        <div class="t-author">
                            <div class="triangle"></div>
                        </div>
                    </div>
                </div>


