<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* This file handles single entries, but only exists for the sake of child theme forward compatibility.

/*remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop', 'tourtiger_sub_contents');*/

function be_landing_page_content(){ ?>
    
    <?php get_template_part('includes/tour_sections_gpm'); ?>
    <?php //get_sidebar('subscribe'); ?>
    
<?php }
add_action( 'be_content_area', 'be_landing_page_content' );
//remove_action('genesis_sidebar', 'genesis_do_sidebar');

// Remove 'site-inner' from structural wrap
add_theme_support( 'genesis-structural-wraps', array( 'header', 'footer-widgets', 'footer' ) );

//genesis();

// Build the page
get_header();
do_action( 'be_content_area' );
get_footer();
