<?php
/* ===========================
 * Flexi Card Class Extend
 * ======================== */
 
class FlexiCard extends StylingCard {

	/**
	 * Return Fields 
	 * @return array
	 */
	function return_acf_group( $i = '', $c = '' ) {

		$fc_options_array = array (
			'key' => 'fc_' . $i . '_ld_5835623e3572c',
			'label' => 'Styles group',
			'name' => $this->slug . '_style-' . $c,
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 1,
			'max' => 1,
			'layout' => 'row',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'fc_' . $i . '_ld_583567303ac0a',
					'label' => 'Card styling',
					'name' => 'card_styling',
					'type' => 'tab',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583562913572d',
					'label' => 'Background',
					'name' => 'fc_style__bg',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'none' => 'None',
						'texture' => 'Texture',
						'color' => 'Color',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'none',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_583562c93572e',
					'label' => 'Background texture',
					'name' => 'fc_style__bg_texture',
					'type' => 'image',
					'instructions' => 'Image will repeat in the card',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583562913572d',
								'operator' => '==',
								'value' => 'texture',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835632ba50b0',
					'label' => 'Backbround color',
					'name' => 'fc_style__bg_color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583562913572d',
								'operator' => '==',
								'value' => 'color',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583563c6c8e78',
					'label' => 'Apply Border',
					'name' => 'fc_style__br',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
						'hover' => 'On Mouseover',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835641cc8e79',
					'label' => 'Border color',
					'name' => 'fc_style__br_color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583563c6c8e78',
								'operator' => '==',
								'value' => 'yes',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583563c6c8e78',
								'operator' => '==',
								'value' => 'hover',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_58356463c8e7b',
					'label' => 'Border Thickness',
					'name' => 'fc_style__br_width',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583563c6c8e78',
								'operator' => '==',
								'value' => 'yes',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583563c6c8e78',
								'operator' => '==',
								'value' => 'hover',
							),
						),
					),
					'wrapper' => array (
						'width' => 30,
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 1,
					'max' => 5,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583564fee9565',
					'label' => 'Apply Dropshadow',
					'name' => 'fc_style__sh',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
						'hover' => 'On Mouseover',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_58356537e9566',
					'label' => 'Apply Padding',
					'name' => 'fc_style__pa',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
						'hover' => 'On Mouseover',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_58356592e9567',
					'label' => 'Padding Thickness',
					'name' => 'fc_style__pa_yes',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58356537e9566',
								'operator' => '==',
								'value' => 'yes',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58356537e9566',
								'operator' => '==',
								'value' => 'hover',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'large' => '20px',
						'medium' => '12px',
						'small' => '5px',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835629usdira',
					'label' => 'Card Radius',
					'name' => 'fc_style__rad',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'fc_' . $i . '_ld_58356537e9566',
								'operator' => '==',
								'value' => 'no'
							)
						)
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'none' => 'None',
						'yep' => 'Set radius',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'none',
					'layout' => 'horizontal',
				),
				array(
					'key' => 'fc_' . $i . '_ld_5835setusdira',
					'label' => 'Set readius',
					'name' => 'fc_style__rad-css',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'fc_' . $i . '_ld_5835629usdira',
								'operator' => '==',
								'value' => 'yep'
							),
							array(
								'field' => 'fc_' . $i . '_ld_58356537e9566',
								'operator' => '==',
								'value' => 'no'
							)
						)
					),
					'default_value' => '',
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placeholder' => '10px or 25%',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583567583ac0b',
					'label' => 'Image styling',
					'name' => '_copy',
					'type' => 'tab',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583567a33ac0c',
					'label' => 'Shadow Overlay',
					'name' => 'fc_style__ov',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'none' => 'None',
						'yes' => 'Yes',
						'grad' => 'Bottom gradient',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835684236cc7',
					'label' => 'Shadow overlay color',
					'name' => 'fc_style__ov_color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583567a33ac0c',
								'operator' => '==',
								'value' => 'yes',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583567a33ac0c',
								'operator' => '==',
								'value' => 'grad',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357a8b56b96',
					'label' => 'Border between Image and Content',
					'name' => 'fc_style__imbo_bet',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable border',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357acd56b97',
					'label' => 'Border Color',
					'name' => 'fc_style__imbo_bet_color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58357a8b56b96',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357af256b98',
					'label' => 'Border Thickness',
					'name' => 'fc_style__imbo_bet_width',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58357a8b56b96',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 1,
					'max' => 5,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357b2a56b99',
					'label' => 'Radius',
					'name' => 'fc_style__imru',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable radius',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357b7256b9a',
					'label' => 'Top Alias',
					'name' => 'fc_style__imru_top',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58357b2a56b99',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 0,
					'max' => 50,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357ba156b9b',
					'label' => 'Bottom Alias',
					'name' => 'fc_style__imru_bottom',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58357b2a56b99',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 0,
					'max' => 50,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583568a136cc9',
					'label' => 'Types of content that should display onto Image',
					'name' => 'fc_style__imdis',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'title' => 'Title',
						'desc' => 'Description',
						'price' => 'Price',
						'label' => 'Label',
					),
					'default_value' => array (
					),
					'layout' => 'horizontal',
					'toggle' => 1,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357283aebcf',
					'label' => 'Text styling',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Styles for text area. This block includes Title, Description and Detail.',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835696b36ccb',
					'label' => 'Text Position',
					'name' => 'fc_style__imte_pos',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'top' => 'Top',
						'center' => 'Center',
						'bottom' => 'Bottom',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835699a36ccc',
					'label' => 'Text Background',
					'name' => 'fc_style__imte_bg',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583569df36ccd',
					'label' => 'Title Decoration',
					'name' => 'fc_style__imte_dec',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'none' => 'None',
						'double' => 'Double line',
						'underline' => 'Single line',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'none',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_58356f96e879f',
					'label' => 'Title Dropshadow',
					'name' => 'fc_style__imte_drsh',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Dropshadow for title',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357042e87a0',
					'label' => 'Title Font',
					'name' => 'fc_style__imte_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357042e87a0-color',
					'label' => 'Title Font Color',
					'name' => 'fc_style__imte_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835718a4dbc5',
					'label' => 'Title Underline',
					'name' => 'fc_style__imte_und',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583571d34dbc6',
					'label' => 'Description Font',
					'name' => 'fc_style__imte_font_des',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583571d34dbc6-color',
					'label' => 'Description Font Color',
					'name' => 'fc_style__imte_font_des-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583571f94dbc7',
					'label' => 'Description Underline',
					'name' => 'fc_style__imte_und_des',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583574ccf3cc9',
					'label' => 'Price styling',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Styles for price area.',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583575d847d26',
					'label' => 'Price Position',
					'name' => 'fc_style__impr_pos',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'content' => 'Beneath Content',
						'top' => 'Top',
						'center' => 'Center',
						'bottom' => 'Bottom',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'center',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835774c26423',
					'label' => 'Price Background',
					'name' => 'fc_style__impr_bg',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835776d26424',
					'label' => 'Price Dropshadow',
					'name' => 'fc_style__impr_shad',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Dropshadow',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583575d847d25',
					'label' => 'Price Font',
					'name' => 'fc_style__impr_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 0,
					'text_align' => 'center',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58357pri7d25-color',
					'label' => 'Price Font Color',
					'name' => 'fc_style__impr_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583576d847d27',
					'label' => 'Price Underline',
					'name' => 'fc_style__impr_font_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835757c47d23',
					'label' => 'Label styling',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'label',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Styles for label area.',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583579625aed3',
					'label' => 'Label Position',
					'name' => 'fc_style__imla_pos',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'label',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'top' => 'Top',
						'center' => 'Center',
						'bottom' => 'Bottom',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'top',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_583579a15aed4',
					'label' => 'Label Font',
					'name' => 'fc_style__imla_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'label',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835aeff-hover',
					'label' => 'On Mouseover effect',
					'name' => 'fc_style__imla_butt_hovef',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'color' => 'Color Invert',
						'text' => 'Text Decoration',
					),
					'default_value' => array (
					),
					'layout' => 'horizontal',
					'toggle' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583579a15aed4-color',
					'label' => 'Label Font Color',
					'name' => 'fc_style__imla_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'label',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583579a15aed4-bg',
					'label' => 'Label Font Background Color',
					'name' => 'fc_style__imla_font-bg',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'label',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583579d15aed5',
					'label' => 'Label Underline',
					'name' => 'fc_style__imla_font_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_583568a136cc9',
								'operator' => '==',
								'value' => 'label',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58358a9d6aa2e',
					'label' => 'Content 1 styling',
					'name' => 'content_1',
					'type' => 'tab',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => '',
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58358acf6aa2f',
					'label' => 'Background color',
					'name' => 'fc_style__co_color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_58358b696aa30',
					'label' => 'Choose what would you like to styling',
					'name' => 'fc_style__co',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'top-border' => 'Top Border',
						'title' => 'Title',
						'desc' => 'Description',
						'price' => 'Price',
						'button' => 'Button',
					),
					'default_value' => array (
					),
					'layout' => 'horizontal',
					'toggle' => 1,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58358c946aa34',
					'label' => 'Top Border',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for Top Border',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58358b946aa31',
					'label' => 'Top Border Width',
					'name' => 'fc_style__co_tobo-w',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'full' => 'Full',
						'half' => 'Half',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'full',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_58358be26aa32',
					'label' => 'Top Border Color',
					'name' => 'fc_style__co_tobo-c',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_58358c346aa33',
					'label' => 'Top Border Thickness',
					'name' => 'fc_style__co_tobo-t',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 1,
					'max' => 5,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583590d533636',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'message',
					'instructions' => '',
					'required' => '',
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters fot Title',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835918633638',
					'label' => 'Title Font',
					'name' => 'fc_style__co_titl_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835918633638-color',
					'label' => 'Title Font Color',
					'name' => 'fc_style__co_titl_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583591db33639',
					'label' => 'Title Underline',
					'name' => 'fc_style__co_titl_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835921c3363a',
					'label' => 'Description',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for description',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583592663363c',
					'label' => 'Description Font',
					'name' => 'fc_style__co_desc_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583592663363c-color',
					'label' => 'Description Font Color',
					'name' => 'fc_style__co_desc_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835927d3363d',
					'label' => 'Description Underline',
					'name' => 'fc_style__co_desc_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359406976e4',
					'label' => 'Price',
					'name' => '_copy',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for price',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583595a4976e5',
					'label' => 'Price Position',
					'name' => 'fc_style__co_pric_pos',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Left',
						'center' => 'Centre',
						'right' => 'Right',
						'u-right' => 'Upper Right',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'left',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_583598f442425',
					'label' => 'Price Font',
					'name' => 'fc_style__co_pric_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 0,
					'text_align' => 0,
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 1,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583598f442425-color',
					'label' => 'Price Font Color',
					'name' => 'fc_style__co_pric_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835992a42426',
					'label' => 'Price Underline',
					'name' => 'fc_style__co_pric_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835994f42427',
					'label' => 'Price Dropshadow',
					'name' => 'fc_style__co_pric_drop',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Dropshadow',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_583599e65dfb8',
					'label' => 'Button',
					'name' => '',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for button',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359a185dfb9',
					'label' => 'Button style',
					'name' => 'fc_style__co_butt_style',
					'type' => 'radio',
					'instructions' => 'Square means non-rounded edges. Round means fully round edges. Rounded corner just means slightly rounded edges.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'text' => 'Text',
						'square' => 'Square',
						'round' => 'Round',
						'corner' => 'Rounded Corner',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'text',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359aa95dfba',
					'label' => 'Button Mouseover effect',
					'name' => 'fc_style__co_butt_hover',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'invert' => 'Color Invert',
						'decor' => 'Text Decoration',
					),
					'default_value' => array (
					),
					'layout' => 'horizontal',
					'toggle' => 1,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359c265dfbb',
					'label' => 'Button position',
					'name' => 'fc_style__co_butt_pos',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Left',
						'center' => 'Center',
						'right' => 'Right',
						'full' => 'Full Width',
						'right-d' => 'Right of Detail',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'left',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a0312a141',
					'label' => 'Button Font',
					'name' => 'fc_style__co_butt_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 0,
					'text_align' => 0,
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a0312a141-color',
					'label' => 'Button Font Color',
					'name' => 'fc_style__co_butt_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a0b52a143',
					'label' => 'Button Background',
					'name' => 'fc_style__co_butt_bg',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a0612a142',
					'label' => 'Button Dropshadow',
					'name' => 'fc_style__co_butt_drop',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Dropshadow',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a0f02a144',
					'label' => 'Button Border',
					'name' => 'fc_style__co_butt_bord',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58359a185dfb9',
								'operator' => '==',
								'value' => 'corner',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
						'hover' => 'On Mouseover',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a1532a145',
					'label' => 'Button Border Thickness',
					'name' => 'fc_style__co_butt_bord_width',
					'type' => 'number',
					'instructions' => 'The border color will be the same as the button font color.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
							array (
								'field' => 'fc_' . $i . '_ld_5835a0f02a144',
								'operator' => '!=',
								'value' => 'no',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 1,
					'max' => 5,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359370976e1',
					'label' => 'Detail',
					'name' => 'detail',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58359c265dfbb',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for detail.',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359391976e2',
					'label' => 'Detail Font',
					'name' => 'fc_style__co_deta_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58359c265dfbb',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359391976e2-color',
					'label' => 'Detail Font Color',
					'name' => 'fc_style__co_deta_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58359c265dfbb',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_58359391976e2-bg',
					'label' => 'Detail Background Color',
					'name' => 'fc_style__co_deta_font-bg',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58359c265dfbb',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_583593c3976e3',
					'label' => 'Detail Underline',
					'name' => 'fc_style__co_deta_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58359c265dfbb',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a275e1990',
					'label' => 'Content 2 styling',
					'name' => 'content_2_styling',
					'type' => 'tab',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'placement' => 'left',
					'endpoint' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a27ae1991',
					'label' => 'Background color',
					'name' => 'fc_style__ct_color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835ch81oobox',
					'label' => 'Choose what would you like to styling',
					'name' => 'fc_style__ct',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'top-border' => 'Top Border',
						'title' => 'Title',
						'desc' => 'Description',
						'price' => 'Price',
						'button' => 'Button',
					),
					'default_value' => array (
					),
					'layout' => 'horizontal',
					'toggle' => 1,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a285e1994',
					'label' => 'Top Border',
					'name' => 'top_border',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for Top Border',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a288e1995',
					'label' => 'Top Border Width',
					'name' => 'fc_style__ct_tobo-w',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'full' => 'Full',
						'half' => 'Half',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'full',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a28ce1996',
					'label' => 'Top Border Color',
					'name' => 'fc_style__ct_tobo-c',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a290e1997',
					'label' => 'Top Border Thickness',
					'name' => 'fc_style__ct_tobo-t',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 1,
					'max' => 5,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a293e1998',
					'label' => 'Title',
					'name' => 'title',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters fot Title',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a295e1999',
					'label' => 'Title Font',
					'name' => 'fc_style__ct_titl_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 1,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a295e1999-color',
					'label' => 'Title Font Color',
					'name' => 'fc_style__ct_titl_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_58358b696aa30',
								'operator' => '==',
								'value' => 'title',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2a0e199b',
					'label' => 'Description',
					'name' => 'description',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for description',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2a3e199c',
					'label' => 'Description Font',
					'name' => 'fc_style__ct_desc_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2a3e199c-color',
					'label' => 'Description Font Color',
					'name' => 'fc_style__ct_desc_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2a6e199d',
					'label' => 'Description Underline',
					'name' => 'fc_style__ct_desc_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'desc',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2b2e19a1',
					'label' => 'Price',
					'name' => 'price',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for price',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2b4e19a2',
					'label' => 'Price Position',
					'name' => 'fc_style__ct_pric_pos',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Left',
						'center' => 'Centre',
						'right' => 'Right',
						'u-right' => 'Upper Right',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'left',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2b7e19a3',
					'label' => 'Price Font',
					'name' => 'fc_style__ct_pric_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 0,
					'text_align' => 0,
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 1,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2b7e19a3-color',
					'label' => 'Price Font Color',
					'name' => 'fc_style__ct_pric_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2bae19a4',
					'label' => 'Price Underline',
					'name' => 'fc_style__ct_pric_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2bde19a5',
					'label' => 'Price Dropshadow',
					'name' => 'fc_style__ct_pric_drop',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'price',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Dropshadow',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2bfe19a6',
					'label' => 'Button',
					'name' => 'button',
					'type' => 'message',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Set parameters for button',
					'new_lines' => '',
					'esc_html' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2c2e19a7',
					'label' => 'Button style',
					'name' => 'fc_style__ct_butt_style',
					'type' => 'radio',
					'instructions' => 'Square means non-rounded edges. Round means fully round edges. Rounded corner just means slightly rounded edges.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'text' => 'Text',
						'square' => 'Square',
						'round' => 'Round',
						'corner' => 'Rounded Corner',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'text',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2c4e19a8',
					'label' => 'Button Mouseover effect',
					'name' => 'fc_style__ct_butt_hover',
					'type' => 'checkbox',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'invert' => 'Color Invert',
						'decor' => 'Text Decoration',
					),
					'default_value' => array (
					),
					'layout' => 'horizontal',
					'toggle' => 1,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2c9e19a9',
					'label' => 'Button position',
					'name' => 'fc_style__ct_butt_pos',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'left' => 'Left',
						'center' => 'Center',
						'right' => 'Right',
						'full' => 'Full Width',
						'right-d' => 'Right of Detail',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'left',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2cbe19aa',
					'label' => 'Button Font',
					'name' => 'fc_style__ct_butt_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 0,
					'text_align' => 0,
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2cbe19aa-color',
					'label' => 'Button Font Color',
					'name' => 'fc_style__ct_butt_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2cee19ab',
					'label' => 'Button Background',
					'name' => 'fc_style__ct_butt_bg',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2d0e19ac',
					'label' => 'Button Dropshadow',
					'name' => 'fc_style__ct_butt_drop',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Dropshadow',
					'default_value' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2d3e19ad',
					'label' => 'Button Border',
					'name' => 'fc_style__ct_butt_bord',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
						'hover' => 'On Mouseover',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'horizontal',
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2d5e19ae',
					'label' => 'Button Border Thickness',
					'name' => 'fc_style__ct_butt_bord_width',
					'type' => 'number',
					'instructions' => 'The border color will be the same as the button font color.',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'top-border',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => 'px',
					'min' => 1,
					'max' => 5,
					'step' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2abe199f',
					'label' => 'Detail Font',
					'name' => 'fc_style__ct_deta_font',
					'type' => 'typography',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835a2c9e19a9',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'show_font_familys' => 1,
					'font-family' => '',
					'show_font_weight' => 1,
					'font-weight' => 400,
					'show_backup_font' => 1,
					'backup-font' => 'Arial, Helvetica, sans-serif',
					'show_text_align' => 1,
					'text_align' => 'left',
					'show_text_direction' => 0,
					'direction' => 'ltr',
					'show_font_size' => 1,
					'font_size' => 20,
					'show_line_height' => 1,
					'line_height' => 25,
					'show_letter_spacing' => 0,
					'letter_spacing' => 0,
					'show_color_picker' => 0,
					'text_color' => '#000000',
					'show_font_style' => 1,
					'font_style' => 'normal',
					'show_preview_text' => 0,
					'default_value' => '',
					'new_lines' => '',
					'maxlength' => '',
					'placeholder' => '',
					'readonly' => 0,
					'disabled' => 0,
					'rows' => '',
					'font_familys' => self::FONTS,
					'stylefont' => array (
						100 => 100,
						300 => 300,
						400 => 400,
						600 => 600,
						700 => 700,
						800 => 800,
					),
					'backupfont' => self::BACK_FONTS,
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2abe199f-color',
					'label' => 'Detail Font Color',
					'name' => 'fc_style__ct_deta_font-color',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835a2c9e19a9',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2abe199f-bg',
					'label' => 'Detail Background Color',
					'name' => 'fc_style__ct_deta_font-bg',
					'type' => 'rgba_color',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835a2c9e19a9',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'rgba' => '',
					'return_value' => 0,
					'ext_value' => array (
					),
				),
				array (
					'key' => 'fc_' . $i . '_ld_5835a2afe19a0',
					'label' => 'Detail Underline',
					'name' => 'fc_style__ct_deta_under',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'fc_' . $i . '_ld_5835a2c9e19a9',
								'operator' => '==',
								'value' => 'right-d',
							),
							array (
								'field' => 'fc_' . $i . '_ld_5835ch81oobox',
								'operator' => '==',
								'value' => 'button',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Enable Underline',
					'default_value' => 0,
				),
			),
		);	

		return $fc_options_array;

	}
	
}

new FlexiCard( 'Flexi Card', 1 );

?>