<?php 

acf_add_local_field_group(array (
	'key' => 'pc_hero_area_root',
	'title' => 'Hero',
	'fields' => array (
		array (
			'key' => 'pc_ha',
			'label' => 'Primary Hero Area',
			'name' => 'pc_hero_area',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Row',
			'min' => '',
			'max' => 1,
			'layouts' => array (
				array (
					'key' => 'pc_ha_la',
					'name' => 'pc_hero',
					'label' => 'Hero',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'pc_ha_tab_2',
							'label' => 'General',
							'name' => 'pc_ha_tab_2',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'field_hero-style',
							'label' => 'Hero Area Style',
							'name' => 'hero_area-style',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => get_pc_styles_list( 'hero_area' ),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'style-one',
						),
						array (
							'key' => 'pc_ha_003-width',
							'label' => 'Hero Width',
							'name' => 'pc_hero_area_banner-width',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'site-grid' => 'Fit in site grid',
								'full' => 'Full width'
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'site-grid',
						),
						array (
							'key' => 'pc_ha_003',
							'label' => 'Hero Height',
							'name' => 'pc_hero_area_size',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'short' => 'Short',
								'medium' => 'Medium',
								'tall' => 'Tall',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'short',
						),
						array (
							'key' => 'pc_ha_009',
							'label' => 'Content Alignment',
							'name' => 'pc_hero_area_align',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Left',
								'middle' => 'Middle',
								'right' => 'right',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'middle',
						),
						array (
							'key' => 'pc_ha_009_3290',
							'label' => 'Text Alignment',
							'name' => 'pc_hero_area_text-align',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Left',
								'center' => 'Center',
								'right' => 'Right',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'center',
						),
						array (
							'key' => 'pc_ha_009-1',
							'label' => 'Content Width',
							'name' => 'pc_hero_area_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'half',
						),
						array (
							'key' => 'pc_ha_009-2',
							'label' => 'Vertical Alignment',
							'name' => 'pc_hero_area_vertical',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'bottom_v' => 'Bottom',
								'middle_v' => 'Middle',
								'top_v' => 'Top',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'middle_v',
						),
						array (
							'key' => 'pc_ha_010-1',
							'label' => 'Downward Arrow',
							'name' => 'pc_ha_downward_arrow',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'message' => 'Enable',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_010-1-10-33',
							'label' => 'Arrow image',
							'name' => 'pc_ha_downward_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
						array (
							'key' => 'pc_ha_010-2',
							'label' => 'Type of bottom divider',
							'name' => 'pc_ha_bd',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'None',
								'repeater' => 'Repeater',
								'image' => 'Image',
								'gradient' => 'Gradient'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'none',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_010-2-1',
							'label' => 'Bottom Divider',
							'name' => 'pc_ha_bd_repeater',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-2',
										'operator' => '==',
										'value' => 'repeater',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						), 
						array (
							'key' => 'pc_ha_010-2-2',
							'label' => 'Bottom Divider',
							'name' => 'pc_ha_bd_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-2',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						), 
						array (
							'key' => 'pc_ha_010-2-3-1',
							'label' => 'Bottom divider',
							'name' => 'pc_ha_bd_gradient',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-2',
										'operator' => '==',
										'value' => 'gradient',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_010-3',
							'label' => 'Overlay',
							'name' => 'pc_ha_overlay',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'None',
								'color' => 'Color',
								'texture' => 'Texture'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'none',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_010-3-1',
							'label' => 'Color',
							'name' => 'pc_ha_overlay_color',
							'type' => 'rgba_color',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-3',
										'operator' => '==',
										'value' => 'color',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_010-3-2',
							'label' => 'Texture',
							'name' => 'pc_ha_overlay_texture',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-3',
										'operator' => '==',
										'value' => 'texture',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						), 
						array (
							'key' => 'pc_ha_tab_1',
							'label' => 'Background',
							'name' => 'pc_ha_tab_1',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_001',
							'label' => 'Image type',
							'name' => 'pc_image_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Single image' => 'Single image',
								'Slider images' => 'Slider images',
								'Background video' => 'Background video',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_002',
							'label' => 'Hero Image',
							'name' => 'pc_hero_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Single image',
									),
								),
							),
							'wrapper' => array (
								'width' => '80',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'large',
							'library' => 'uploadedTo',
							'return_format' => 'array',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
						array (
							'key' => 'pc_ha_002-1',
							'label' => 'Fixed',
							'name' => 'pc_ha_image-fixed',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Single image',
									),
								),
							),
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'hero-area_image_fixed-no',
							'layout' => 'vertical',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_004',
							'label' => 'Hero Slides',
							'name' => 'pc_hero_slides',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Slider images',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'thumbnail',
							'library' => 'uploadedTo',
							'min' => 0,
							'max' => 0,
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
							'insert' => 'append',
						),
						array (
							'key' => 'pc_ha_005',
							'label' => 'Hero Video mp4',
							'name' => 'pc_hero_video',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_006',
							'label' => 'Hero Video webm',
							'name' => 'pc_hero_video_webm',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_007',
							'label' => 'Hero Video ogv',
							'name' => 'pc_hero_video_ogv',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_008',
							'label' => 'Video Poster',
							'name' => 'pc_video_poster',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'full',
							'library' => 'uploadedTo',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'pc_ha_tab_3',
							'label' => 'First title',
							'name' => 'pc_ha_tab_3',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_013-1-1',
							'label' => 'Title',
							'name' => 'pc_ha_1-tit',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_013-1-2',
							'label' => 'HR line',
							'name' => 'pc_ha_1-tit_hr',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'message' => 'Add',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_013-1-3',
							'label' => 'SEO Tag',
							'name' => 'pc_ha_1-tit_seo',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'h1' => 'H1',
								'h2' => 'H2',
								'h3' => 'H3',
								'h4' => 'H4',
								'h5' => 'H5',
								'h6' => 'H6'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'h2',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_013-2-3-1',
							'label' => 'HR Color',
							'name' => 'pc_ha_1-tit_hr-c',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_013-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_013-2-3-2',
							'label' => 'HR Width',
							'name' => 'pc_ha_1-tit_hr-w',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_013-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'quarter' => '¼',
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'full',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_013-2-3-3',
							'label' => 'HR Image',
							'name' => 'pc_ha_1-tit_hr-i',
							'type' => 'image',
							'instructions' => 'Replace with image',
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_013-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => ''
						),
						array (
							'key' => 'pc_ha_tab_4',
							'label' => 'Second title',
							'name' => 'pc_ha_tab_4',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_014-1-1',
							'label' => 'Title',
							'name' => 'pc_ha_2-tit',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_014-1-2',
							'label' => 'HR line',
							'name' => 'pc_ha_2-tit_hr',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'message' => 'Add',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_014-1-3',
							'label' => 'SEO Tag',
							'name' => 'pc_ha_2-tit_seo',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'h1' => 'H1',
								'h2' => 'H2',
								'h3' => 'H3',
								'h4' => 'H4',
								'h5' => 'H5',
								'h6' => 'H6'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'h2',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_014-2-3-1',
							'label' => 'HR Color',
							'name' => 'pc_ha_2-tit_hr-c',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_014-2-3-2',
							'label' => 'HR Width',
							'name' => 'pc_ha_2-tit_hr-w',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'quarter' => '¼',
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'full',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_014-2-3-3',
							'label' => 'HR Image',
							'name' => 'pc_ha_2-tit_hr-i',
							'type' => 'image',
							'instructions' => 'Replace with image',
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => ''
						),
						array (
							'key' => 'pc_ha_tab_5',
							'label' => 'Third title',
							'name' => 'pc_ha_tab_5',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_015-1-1',
							'label' => 'Title',
							'name' => 'pc_ha_3-tit',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_015-1-2',
							'label' => 'HR line',
							'name' => 'pc_ha_3-tit_hr',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'message' => 'Add',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_015-1-3',
							'label' => 'SEO Tag',
							'name' => 'pc_ha_3-tit_seo',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'h1' => 'H1',
								'h2' => 'H2',
								'h3' => 'H3',
								'h4' => 'H4',
								'h5' => 'H5',
								'h6' => 'H6'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'h2',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_015-2-3-1',
							'label' => 'HR Color',
							'name' => 'pc_ha_3-tit_hr-c',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_015-2-3-2',
							'label' => 'HR Width',
							'name' => 'pc_ha_3-tit_hr-w',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'quarter' => '¼',
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'full',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_015-2-3-3',
							'label' => 'HR Image',
							'name' => 'pc_ha_3-tit_hr-i',
							'type' => 'image',
							'instructions' => 'Replace with image',
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => ''
						),
						
						array (
							'key' => 'pc_ha_tab_6',
							'label' => 'Button',
							'name' => 'pc_ha_tab_6',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_013',
							'label' => 'CTA Button text',
							'name' => 'pc_cta_button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_014',
							'label' => 'Button link type',
							'name' => 'pc_button_link_type',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Custom' => 'Custom',
								'iframe-popup' => 'iFrame Popup',
								'Video' => 'Video',
								'Search Box' => 'Search Box',
							),
						),
						array (
							'key' => 'pc2131012133',
							'label' => 'CTA Button link',
							'name' => 'pc_cta_button_url',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Custom' 
									)
								),
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'iframe-popup' 
									)
								)
							),
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'https://example.com',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_014_1',
							'label' => 'Search settings',
							'name' => 'search_settings_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Search by date range' => 'Search by date range',
								'Search by one date' => 'Search by one date',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'Search by date range',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_014_2',
							'label' => 'Search by categories',
							'name' => 'search_settings_type_category',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'message' => 'Yes',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_014_3',
							'label' => 'Select categories',
							'name' => 'search_settings_type_category_select',
							'type' => 'advanced_taxonomy_selector',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
											'field' => 'pc_ha_014_2',
											'operator' => '==',
											'value' => '1',
										),
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'data_type' => 'terms',
							'taxonomies' => array (
								0 => 'rezdy_cat',
								1 => 'tour_cat',
							),
							'post_type' => array (
								0 => 'product',
								1 => 'tour',
							),
							//'field_type' => 'multiselect',
							'field_type' => 'select',
							'allow_null' => 1,
							'return_value' => 'object',
						),
						array (
							'key' => 'field_552061311b125_settings_type_category_hide_option_pc',
							'label' => 'Hide categories option in search result page',
							'name' => 'search_settings_type_category_hide_option',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
											'field' => 'pc_ha_014_2',
											'operator' => '==',
											'value' => '1',
										),
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
						),
						array (
							'key' => 'field_54e613c087d24_special_message_pc',
							'label' => 'Special message above search results',
							'name' => 'search_settings_type_special_message',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_589c6dc1d2748_datepicker_position_pc',
							'label' => 'Datepicker position',
							'name' => 'search_settings_type_datepicker_position',
							'type' => 'checkbox',
							'instructions' => 'Default drop down and open right',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'drop-up' => 'drop-up',
								// 'left' => 'left',
							),
							'default_value' => array (
							),
							'layout' => 'horizontal',
							'toggle' => 0,
						),

						
						array (
							'key' => 'pc_ha_tab_6_addt',
							'label' => 'Button 2',
							'name' => 'pc_ha_tab_6_addt',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_013_addt',
							'label' => 'CTA Button text',
							'name' => 'pc_cta_button_text_addt',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_014_addt',
							'label' => 'Button link type',
							'name' => 'pc_button_link_type_addt',
							'type' => 'select',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '33',
							),
							'choices' => array (
								'Custom' => 'Custom',
								'iframe-popup' => 'iFrame Popup',
							),
						),
						array (
							'key' => 'pc2131012133_addt',
							'label' => 'CTA Button link',
							'name' => 'pc_cta_button_url_addt',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014_addt',
										'operator' => '==',
										'value' => 'Custom' 
									)
								),
								array (
									array (
										'field' => 'pc_ha_014_addt',
										'operator' => '==',
										'value' => 'iframe-popup' 
									)
								)
							),
							'wrapper' => array (
								'width' => '33',
							),
							'default_value' => '',
							'placeholder' => 'https://example.com',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						
						array (
							'key' => 'pc_ha_tab_7',
							'label' => 'Mobile devices',
							'name' => 'pc_ha_tab_7',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_015-a',
							'label' => 'Action button',
							'name' => 'pc_ha_action_button',
							'type' => 'true_false',
							'required' => 0,
							'wrapper' => array (
								'width' => '30',
							),
							'message' => 'Show button underneath Hero Area',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_015-b',
							'label' => 'Label',
							'name' => 'pc_ha_action_button_label',
							'type' => 'text',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-a',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '35',
							),
							'placeholder' => 'Book now',
						),
						array (
							'key' => 'pc_ha_015-c',
							'label' => 'Destination',
							'name' => 'pc_ha_action_button_url',
							'type' => 'text',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-a',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '35',
							),
							'placeholder' => 'https://example.com',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/test-pc.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'categories',
		8 => 'tags',
		9 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
)); 

?>