<?php 

acf_add_local_field_group(array (
	'key' => 'group_557b163001178',
	'title' => 'Hero',
	'fields' => array (
		array (
			'key' => 'pc_ha',
			'label' => 'Primary Hero Area',
			'name' => 'pc_hero_area',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'button_label' => 'Add Row',
			'min' => '',
			'max' => 1,
			'layouts' => array (
				array (
					'key' => 'pc_ha_la',
					'name' => 'pc_hero',
					'label' => 'Hero',
					'display' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'pc_ha_tab_2',
							'label' => 'General',
							'name' => 'pc_ha_tab_2',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_003',
							'label' => 'Hero Height',
							'name' => 'pc_hero_area_size',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'short' => 'Short',
								'medium' => 'Medium',
								'tall' => 'Tall',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'short',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_009',
							'label' => 'Content Alignment',
							'name' => 'pc_hero_area_align',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Left',
								'middle' => 'Middle',
								'right' => 'Center',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'middle',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_009-1',
							'label' => 'Content Width',
							'name' => 'pc_hero_area_width',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'half',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_009-2',
							'label' => 'Vertical Alignment',
							'name' => 'pc_hero_area_vertical',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '25',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'bottom_v' => 'Bottom',
								'middle_v' => 'Middle',
								'top_v' => 'Top',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'middle_v',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_010-1',
							'label' => 'Downward Arrow',
							'name' => 'pc_ha_downward_arrow',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'message' => 'Enable',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_010-2',
							'label' => 'Type of bottom divider',
							'name' => 'pc_ha_bd',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'None',
								'repeater' => 'Repeater',
								'image' => 'Image',
								'gradient' => 'Gradient'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'none',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_010-2-1',
							'label' => 'Bottom Divider',
							'name' => 'pc_ha_bd_repeater',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-2',
										'operator' => '==',
										'value' => 'repeater',
									),
								),
							),
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						), 
						array (
							'key' => 'pc_ha_010-2-2',
							'label' => 'Bottom Divider',
							'name' => 'pc_ha_bd_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-2',
										'operator' => '==',
										'value' => 'image',
									),
								),
							),
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						), 
						array (
							'key' => 'pc_ha_010-2-3-1',
							'label' => 'Bottom divider',
							'name' => 'pc_ha_bd_gradient',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-2',
										'operator' => '==',
										'value' => 'gradient',
									),
								),
							),
							'wrapper' => array (
								'width' => '40',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_010-3',
							'label' => 'Overlay',
							'name' => 'pc_ha_overlay',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'None',
								'color' => 'Color',
								'texture' => 'Texture'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'none',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_010-3-1',
							'label' => 'Color',
							'name' => 'pc_ha_overlay_color',
							'type' => 'rgba_color',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-3',
										'operator' => '==',
										'value' => 'color',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_010-3-2',
							'label' => 'Texture',
							'name' => 'pc_ha_overlay_texture',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_010-3',
										'operator' => '==',
										'value' => 'texture',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						), 
						array (
							'key' => 'pc_ha_tab_1',
							'label' => 'Background',
							'name' => 'pc_ha_tab_1',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_001',
							'label' => 'Image type',
							'name' => 'pc_image_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Single image' => 'Single image',
								'Slider images' => 'Slider images',
								'Background video' => 'Background video',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_002',
							'label' => 'Hero Image',
							'name' => 'pc_hero_image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Single image',
									),
								),
							),
							'wrapper' => array (
								'width' => '80',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'large',
							'library' => 'uploadedTo',
							'return_format' => 'array',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
						),
						array (
							'key' => 'pc_ha_002-1',
							'label' => 'Fixed',
							'name' => 'pc_ha_image-fixed',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Single image',
									),
								),
							),
							'wrapper' => array (
								'width' => '20',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'hero-area_image_fixed-no' => 'No',
								'hero-area_image_fixed' => 'Yes',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'hero-area_image_fixed-no',
							'layout' => 'vertical',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_004',
							'label' => 'Hero Slides',
							'name' => 'pc_hero_slides',
							'type' => 'gallery',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Slider images',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'thumbnail',
							'library' => 'uploadedTo',
							'min' => 0,
							'max' => 0,
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => '',
							'insert' => 'append',
						),
						array (
							'key' => 'pc_ha_005',
							'label' => 'Hero Video mp4',
							'name' => 'pc_hero_video',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_006',
							'label' => 'Hero Video webm',
							'name' => 'pc_hero_video_webm',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_007',
							'label' => 'Hero Video ogv',
							'name' => 'pc_hero_video_ogv',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_008',
							'label' => 'Video Poster',
							'name' => 'pc_video_poster',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_001',
										'operator' => '==',
										'value' => 'Background video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'id',
							'preview_size' => 'full',
							'library' => 'uploadedTo',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array (
							'key' => 'pc_ha_tab_3',
							'label' => 'First title',
							'name' => 'pc_ha_tab_3',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_013-1-1',
							'label' => 'Title',
							'name' => 'pc_ha_1-tit',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_013-1-2',
							'label' => 'HR line',
							'name' => 'pc_ha_1-tit_hr',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'message' => 'Add',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_013-1-3',
							'label' => 'SEO Tag',
							'name' => 'pc_ha_1-tit_seo',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'h1' => 'H1',
								'h2' => 'H2',
								'h3' => 'H3',
								'h4' => 'H4',
								'h5' => 'H5',
								'h6' => 'H6'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'h2',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_013-2-3-1',
							'label' => 'HR Color',
							'name' => 'pc_ha_1-tit_hr-c',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_013-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_013-2-3-2',
							'label' => 'HR Width',
							'name' => 'pc_ha_1-tit_hr-w',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_013-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'quarter' => '¼',
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'full',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_013-2-3-3',
							'label' => 'HR Image',
							'name' => 'pc_ha_1-tit_hr-i',
							'type' => 'image',
							'instructions' => 'Replace with image',
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_013-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => ''
						),
						array (
							'key' => 'pc_ha_tab_4',
							'label' => 'Second title',
							'name' => 'pc_ha_tab_4',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_014-1-1',
							'label' => 'Title',
							'name' => 'pc_ha_2-tit',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_014-1-2',
							'label' => 'HR line',
							'name' => 'pc_ha_2-tit_hr',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'message' => 'Add',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_014-1-3',
							'label' => 'SEO Tag',
							'name' => 'pc_ha_2-tit_seo',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'h1' => 'H1',
								'h2' => 'H2',
								'h3' => 'H3',
								'h4' => 'H4',
								'h5' => 'H5',
								'h6' => 'H6'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'h2',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_014-2-3-1',
							'label' => 'HR Color',
							'name' => 'pc_ha_2-tit_hr-c',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_014-2-3-2',
							'label' => 'HR Width',
							'name' => 'pc_ha_2-tit_hr-w',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'quarter' => '¼',
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'full',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_014-2-3-3',
							'label' => 'HR Image',
							'name' => 'pc_ha_2-tit_hr-i',
							'type' => 'image',
							'instructions' => 'Replace with image',
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => ''
						),
						array (
							'key' => 'pc_ha_tab_5',
							'label' => 'Third title',
							'name' => 'pc_ha_tab_5',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_015-1-1',
							'label' => 'Title',
							'name' => 'pc_ha_3-tit',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_015-1-2',
							'label' => 'HR line',
							'name' => 'pc_ha_3-tit_hr',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'message' => 'Add',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_015-1-3',
							'label' => 'SEO Tag',
							'name' => 'pc_ha_3-tit_seo',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'h1' => 'H1',
								'h2' => 'H2',
								'h3' => 'H3',
								'h4' => 'H4',
								'h5' => 'H5',
								'h6' => 'H6'
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'h2',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_015-2-3-1',
							'label' => 'HR Color',
							'name' => 'pc_ha_3-tit_hr-c',
							'type' => 'rgba_color',
							'instructions' => 'The color would fade out at the bottom',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'rgba' => '',
							'return_value' => 0,
							'ext_value' => array (
							),
						),
						array (
							'key' => 'pc_ha_015-2-3-2',
							'label' => 'HR Width',
							'name' => 'pc_ha_3-tit_hr-w',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'quarter' => '¼',
								'half' => '½',
								'third' => '¾',
								'full' => 'Full',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'full',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_015-2-3-3',
							'label' => 'HR Image',
							'name' => 'pc_ha_3-tit_hr-i',
							'type' => 'image',
							'instructions' => 'Replace with image',
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_015-1-2',
										'operator' => '==',
										'value' => 1,
									),
								),
							),
							'wrapper' => array (
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'preview_size' => 'medium',
							'library' => 'uploadedTo',
							'return_format' => 'url',
							'min_width' => 0,
							'min_height' => 0,
							'min_size' => 0,
							'max_width' => 0,
							'max_height' => 0,
							'max_size' => 0,
							'mime_types' => ''
						),

						array (
							'key' => 'pc_ha_tab_6',
							'label' => 'Button',
							'name' => 'pc_ha_tab_6',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array (
							'key' => 'pc_ha_013',
							'label' => 'CTA Button text',
							'name' => 'pc_cta_button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'none',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_014',
							'label' => 'Button link type',
							'name' => 'pc_button_link_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Custom' => 'Custom',
								'Link to Featured tours' => 'Link to Featured tours',
								'Use as third party integration Link' => 'Use as third party integration Link',
								'Play Video' => 'Play Video',
								'Search Box' => 'Search Box',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_014_1',
							'label' => 'Search settings',
							'name' => 'pc_search_settings_type',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Search by date range' => 'Search by date range',
								'Search by one date' => 'Search by one date',
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'Search by date range',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_014_2',
							'label' => 'Search by categories',
							'name' => 'pc_search_settings_type_category',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Search Box',
									),
								),
							),
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'message' => 'Yes',
							'default_value' => 0,
						),
						array (
							'key' => 'pc_ha_014_3',
							'label' => 'Select categories',
							'name' => 'pc_search_settings_type_category_select',
							'type' => 'taxonomy',
							'instructions' => 'the default is the current category',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014_2',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'taxonomy' => 'tour_cat',
							'field_type' => 'multi_select',
							'allow_null' => 1,
							'add_term' => 1,
							'save_terms' => 0,
							'load_terms' => 0,
							'return_format' => 'object',
							'multiple' => 0
						),
						array (
							'key' => 'pc_ha_015',
							'label' => 'Third party',
							'name' => 'pc_third_party',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Use as third party integration Link',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
							),
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'allow_null' => 0,
						),
						array (
							'key' => 'pc_ha_016',
							'label' => 'Video Button link',
							'name' => 'pc_video_button_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Play Video',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_017',
							'label' => 'CTA Button link',
							'name' => 'pc_book_tours_link',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Custom',
									),
									array (
										'field' => 'pc_ha_012',
										'operator' => '!=',
										'value' => '1',
									),
								),
								array (
									array (
										'field' => 'pc_ha_014',
										'operator' => '==',
										'value' => 'Use as third party integration Link',
									),
									array (
										'field' => 'pc_ha_012',
										'operator' => '!=',
										'value' => '1',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'http://',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_019',
							'label' => 'CTA onclick',
							'name' => 'pc_cta_onclick',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'pc_ha_020',
							'label' => 'CTA Button radius',
							'name' => 'pc_cta_button_radius',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'min' => '',
							'max' => '',
							'step' => 1,
							'readonly' => 0,
							'disabled' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/test-pc.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'the_content',
		1 => 'custom_fields',
		2 => 'discussion',
		3 => 'comments',
		4 => 'slug',
		5 => 'author',
		6 => 'format',
		7 => 'categories',
		8 => 'tags',
		9 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
)); 

?>